//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

pub mod prelude;
pub mod header_message;
pub mod request_user;
pub mod shared_data;
pub mod weather_forecast;
pub mod request_task;
pub mod response_task;
pub mod tasks;
pub mod users;
